# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

["tw63026.ap-northeast-2.aws"]
account = "tw63026.ap-northeast-2.aws"
user = "Shreya"
password = "Goodluck@246"
role = "HOL_ROLE"
warehouse = "HOL_WH"
database = "HOL_DB"
schema = "ANALYTICS"
